### ISSUE TITLE
Nouvel entraînement - saisie des joueurs

### ISSUE THREAD

**Issue by FDehove** [Alpha-Lin/planning_club_de_tennis#1]
En admin :
- Je commence à créer un entraînement : je choisis un jour, heure_début, heure_fin, entraîneur.
- Je clique sur Ajouter un utilisateur et je vois "Elève 1 Echaroux Stéphanie"
- Je change le nom de l'utilisateur pour "Brocheriou Isabelle"
- Je clique sur Ajouter un utilisateur et là arrive le bug :
"Elève 1 Echaroux Stéphanie" (alors que j'avais changé)
"Elève 2 Echaroux Stéphanie"

Autrement dit, si je modifie les noms au fur et à mesure, à chaque clic sur
"Ajouter un utilisateur", tout est reseter sur "Elève X Echaroux Stéphanie"

**Comment by Alpha-Lin** [comment]
Problème résolue, au lieu d'ajouter les dropdowns avec un `innerHTML ` j'ai utilisé la méthode `appendChild()` qui ne réinitialise pas le contenu HTML. 

commit : 54350edc2c6938b90503cdc381b122fab7a39017

**Comment by FDehove** [comment]
Le bouton "Ajouter un joueur" n'agit plus.

Attend un peu avant de fermer, un exemple de cycle de bug avec bugzilla :


![image](https://user-images.githubusercontent.com/64779602/103350312-d775a900-4a9f-11eb-94bf-cd2717788cf6.png)

:-)

**Comment by Alpha-Lin** [comment]
J'ai eu le même problème, pour moi ça venait du cache qu'il fallait juste rafraîchir.

**Comment by FDehove** [comment]
Ok, c'est bon après rafraichissement.
